name: Create New Short Link
description: Add a new redirect page
labels: ["short-link"]
body:
  - type: input
    id: target_url
    attributes:
      label: "Target URL"
      placeholder: "https://example.com/destination"
    validations:
      required: true
